
[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
    -D CONFIG_FREERTOS_UNICORE=0

lib_deps =
    mathertel/RotaryEncoder @ ^1.5.3
    br3ttb/PID @ ^1.2.1
    waspinator/AccelStepper @ ^1.64
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4

monitor_rts = 0
monitor_dtr = 0
